Repository moonbamijam/sassy-css, pull requests merged in 2024-08, with the labels that each got.

#23 chore: add github actions deployment
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
  .gitignore
  src/components/sections/gap/GapSection.tsx
  src/components/sections/margin/MarginSection.tsx
Labels: for: devops, type: chore

#26 feat: add font family section
  src/App.tsx
  src/components/sections/color/ColorSection.tsx
  src/components/sections/font/family/FontFamilySection.tsx
  src/components/sections/font/family/font-family.module.scss
  src/components/sections/gap/GapSection.tsx
  src/components/sections/margin/MarginSection.tsx
  src/components/sections/padding/PaddingSection.tsx
  src/components/ui/card/Card.tsx
  src/components/ui/card/card.module.scss
  src/lib/fontFamiles.ts
  src/styles/globals.scss
  src/utils/replaceSpacesToDash.ts
Labels: for: ui/ux, status: in progress, type: feature

#30 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: documentation, for: devops, status: completed
